name: Email Step Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 21f3000031@ds.study.iitm.ac.in
        run: echo "Hello, world!"
